### PR TITLE
support after suite callbacks

### PR DESCRIPTION
**Pull request by eudoxa**
Currently, rrrspec does not support "config.after(:suite)".
This pr may work well but I can not add the test. It’s over my head.

### CODE REVIEW

**Comment by k0kubun** [comment]
LGTM

**Comment by eagletmt** [comment]
LGTM.

> This pr may work well but I can not add the test. It’s over my head.

Add `config.after(:suite)` case to local_test specs. We can check the behavior manually.

**Comment by eudoxa** [comment]
I setuped local_test and tried to write spec. 
However,  Writing the test of 'config.after(:suite)' is difficult for me. I have no idea.

Could I merge it without tests?

**Comment by eagletmt** [comment]
:ok:

**Pull request merged**
